### ISSUE TITLE
Error: 'import-twitter' is not a registered wp command. See 'wp help' for available commands.

### ISSUE THREAD

**Issue by jasontucker** [shawnhooper/twitter-archive-to-wp#1] opened 2022-11-14 17:43 UTC
I get this error when running the command in terminal. Plugin is installed and I can see the post type showing up in the dashboard sidebar but the command doesn't work.

wp import-twitter --author=jasontucker
Error: 'import-twitter' is not a registered wp command. See 'wp help' for available commands.

Looking in my list of commands **wp help**
  export                 Exports WordPress content to a WXR file.
  google-site-kit
  help                   Gets help on WP-CLI, or on a specific command.
  i18n                   Provides internationalization tools for WordPress projects.
  import                 Imports content from a given WXR file.
  jetpack                Control your local Jetpack installation.
  jetpack-heartbeat      Interact with the Heartbeat
  jetpack-waf            Just a few sample commands to learn how WP-CLI works
  language               Installs, activates, and manages language packs.
  maintenance-mode       Activates, deactivates or checks the status of the maintenance mode of a site.
  media                  Imports files as attachments, regenerates thumbnails, or lists registered image sizes.

**Comment by shawnhooper** [comment] 2022-11-14 18:09
@jasontucker can you try again? I just pushed an update. 

Instead of using your username use the ID for the post author. 

Ex:
wp import-Twitter 1 

Where 1 is your user Id. 

Note: in latest update you won't see the UI until the import is run.

**Comment by jasontucker** [comment] 2022-11-14 18:54
looked in the database and my account number is 1 so I ran the folowing command:

/sites/jasontucker.blog/files$ wp import-Twitter 1
Error: 'import-Twitter' is not a registered wp command. See 'wp help' for available commands.

I also tried:
/sites/jasontucker.blog/files$wp import-twitter --author=1
Error: 'import-Twitter' is not a registered wp command. See 'wp help' for available commands.

I'm thinking the command isn't registered even though the plugin is installed.

**Comment by shawnhooper** [comment] 2022-11-14 18:55
Oops. import-twitter should be lowercase. That's my bad. Typed my last reply to you on my phone.

**Comment by jasontucker** [comment] 2022-11-14 18:58
Yeah that didnt work either, its also not showing up in the wp help command as a valid command.

/sites/jasontucker.blog/files$ wp import-twitter 1
Error: 'import-twitter' is not a registered wp command. See 'wp help' for available commands.

`  wp <command>

SUBCOMMANDS

  cache                  Adds, removes, fetches, and flushes the WP Object Cache object.
  cap                    Adds, removes, and lists capabilities of a user role.
  cli                    Reviews current WP-CLI info, checks for updates, or views defined aliases.
  comment                Creates, updates, deletes, and moderates comments.
  config                 Generates and reads the wp-config.php file.
  core                   Downloads, installs, updates, and manages a WordPress installation.
  cron                   Tests, runs, and deletes WP-Cron events; manages WP-Cron schedules.
  db                     Performs basic database operations using credentials stored in wp-config.php.
  embed                  Inspects oEmbed providers, clears embed cache, and more.
  eval                   Executes arbitrary PHP code.
  eval-file              Loads and executes a PHP file.
  export                 Exports WordPress content to a WXR file.
  google-site-kit
  help                   Gets help on WP-CLI, or on a specific command.
  i18n                   Provides internationalization tools for WordPress projects.
  import                 Imports content from a given WXR file.
  jetpack                Control your local Jetpack installation.
  jetpack-heartbeat      Interact with the Heartbeat
  jetpack-waf            Just a few sample commands to learn how WP-CLI works
  language               Installs, activates, and manages language packs.
  maintenance-mode       Activates, deactivates or checks the status of the maintenance mode of a site.
  media                  Imports files as attachments, regenerates thumbnails, or lists registered image sizes.
  menu                   Lists, creates, assigns, and deletes the active theme's navigation menus.
  network                Perform network-wide operations.
  option                 Retrieves and sets site options, including plugin and WordPress settings.
  package                Lists, installs, and removes WP-CLI packages.
  plugin                 Manages plugins, including installs, activations, and updates.
  post                   Manages posts, content, and meta.
  post-type              Retrieves details on the site's registered post types.
  rewrite                Lists or flushes the site's rewrite rules, updates the permalink structure.
  role                   Manages user roles, including creating new roles and resetting to defaults.
  scaffold               Generates code for post types, taxonomies, plugins, child themes, etc.
  search-replace         Searches/replaces strings in the database.
  server                 Launches PHP's built-in web server for a specific WordPress installation.
  shell                  Opens an interactive PHP console for running and testing PHP code.
  sidebar                Lists registered sidebars.
  site                   Creates, deletes, empties, moderates, and lists one or more sites on a multisite installation.
  spinupwp               Perform SpinupWP operations.
  super-admin            Lists, adds, or removes super admin users on a multisite installation.
  taxonomy               Retrieves information about registered taxonomies.
  term                   Manages taxonomy terms and term meta, with create, delete, and list commands.
  theme                  Manages themes, including installs, activations, and updates.
  transient              Adds, gets, and deletes entries in the WordPress Transient Cache.
  user                   Manages users, along with their roles, capabilities, and meta.
  widget                 Manages widgets, including adding and moving them within sidebars.`

**Comment by shawnhooper** [comment] 2022-11-14 19:01
@jasontucker hmmm. Ok. I'll have to check it out when I get to my destination. Hate to use the line "it works on my local" but ... it does.

Sorry for the pain.

**Comment by jasontucker** [comment] 2022-11-14 19:01
I'm just being a good tester over here. Let me know if there is anything i can do for ya.

**Comment by shawnhooper** [comment] 2022-11-14 20:09
@jasontucker Which version of WP-CLI are you running? 

`wp cli version` to find out.

**Comment by jasontucker** [comment] 2022-11-14 20:48
/sites/jasontucker.blog/files$ wp cli version
WP-CLI 2.6.0

**Comment by jasontucker** [comment] 2022-11-14 20:52
sudo wp cli update
[sudo] password for jtucker:
You have version 2.6.0. Would you like to update to 2.7.1? [y/n] Y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v2.7.1/wp-cli-2.7.1.phar...
md5 hash verified: 7bc3c3122d8b89b7b5da8c94bda55f4e
New version works. Proceeding to replace.
Success: Updated WP-CLI to 2.7.1.

/sites/jasontucker.blog/files$ wp cli version
WP-CLI 2.7.1

/sites/jasontucker.blog/files$ wp import-twitter 1
Error: 'import-twitter' is not a registered wp command. See 'wp help' for available commands.

even after updating that didnt fix it. It looks like the command isnt being registered

**Comment by shawnhooper** [comment] 2022-11-14 23:26
<img width="816" alt="image" src="https://user-images.githubusercontent.com/2073284/201788940-22cff01d-f00e-4d41-b7d6-ddde2deee5b6.png">

Strange, it shows up for me.  I'll do some digging and see what could cause it not to register....

**Comment by shawnhooper** [comment] 2022-11-30 05:16
@jasontucker I've just released a new version of the plugin.  I'm curious if it's working for you now.  Mind testing when you have a few minutes?

**Comment by stoursailor** [comment] 2022-12-03 20:54
> I get this error when running the command in terminal. Plugin is installed and I can see the post type showing up in the dashboard sidebar but the command doesn't work.
> 
> wp import-twitter --author=jasontucker Error: 'import-twitter' is not a registered wp command. See 'wp help' for available commands.
> 
> Looking in my list of commands **wp help** export Exports WordPress content to a WXR file. google-site-kit help Gets help on WP-CLI, or on a specific command. i18n Provides internationalization tools for WordPress projects. import Imports content from a given WXR file. jetpack Control your local Jetpack installation. jetpack-heartbeat Interact with the Heartbeat jetpack-waf Just a few sample commands to learn how WP-CLI works language Installs, activates, and manages language packs. maintenance-mode Activates, deactivates or checks the status of the maintenance mode of a site. media Imports files as attachments, regenerates thumbnails, or lists registered image sizes.

Same issue here.

**Comment by shawnhooper** [comment] 2022-12-03 21:30
@stoursailor Thanks for letting me know.  Out of curiosity what version of WP and PHP are you running?

**Comment by stoursailor** [comment] 2022-12-03 21:40
Hi Shawn. I'm running WordPress 6.1.1 & PHP 8.0.

**Comment by shawnhooper** [comment] 2022-12-03 22:00
Thanks @stoursailor.   Same as me.  I'll keep playing around to see if I can figure out why the command isn't recognized for some users.

**Comment by shawnhooper** [comment] 2022-12-31 16:59
@stoursailor 

Discussing this with some users on Mastodon, and believe we found the problem to be isolated to sites running WordPress Multisite.  In which case you need to either Network Activate the plugin, or specify the site you want to run WP-CLI on using the --url parameter.

**Comment by shawnhooper** [comment] 2023-01-24 02:19
I'm going to close this issue for now. I believe this was caused by Multisite installs.

**Closed as completed** 2023-01-24 02:19 UTC
